<section class="section section-lg">
        <div class="container">
          <div class="row">
            <div class="col-xl-12">
              <!-- Terms list-->
              <dl class="list-terms">
                <h1 class="text-center">HISTORY</h1>
                <dd class="text-center m-4">The people of Awgu geographical circumscription were a deeply religious people; who before the advent of Christianity in Igboland had a common religious heritage of a belief in One, Unseen, Omnipotent God. This Almighty God was referred to as Ali Awgu (the Awgu earth goddess). No wonder such popular expression as "Ali Awgu chewe nwawu" (Ali Awgu protect your child) is common among Awgu people. This belief and sense of sacred in this Ali Awgu is peculiar to Awgu people. The belief and sense of sacred in this Ali Awgu is peculiar to Awgu religious tradition permeated and prevailed over the social, moral, spiritual, mutual and stereological background of the people before the beginning of the Christian religion.
                The remotest beginning of the Catholic presence in the Awgu division dates back to the acts of the French Catholic Missionaries that came to Eastern Nigeria under Fr. J. E. Luts in 1885 pitching their first tent at Holy Trinity in Onitsha. The evangelical activities of these French Holy Ghost missionaries spread to Enugu Section and consequently to Awgu sub-section by the early years of 20th century. The missionary development in Awgu came mainly from Eke town in Udi division, and partly from Uturu in Okigwe. What we call Awgu Diocese today is therefore historical effect of synthetic, missionary roles and contributes from Eke and Uturu Catholic Missions.
                As early as 1912, Chief Onyeama (the warrant paramount Chief of Eke town) in his bid to attract Western education for his children and people, had gathered a handful of people (Catechumen) amidst the already existing Anglican adherents that were found around Eke and Abor towns.
                His invitation to the Catholic Missionaries brought Fr. Joseph Shanahan to Eke in 1914; who laid the first foundation of the old Eke Parish/School out of which sprang the spread of other Catholic Missions in the current Enugu part of Eastern Nigeria. As the incumbent and first Bishop of Awgu, Rt. Rev. Dr. J. I. Okoye wrote in his B.D. Thesis, Christianity in Mbanabo, its Advent growth, and Future, "It was indeed at Eke that the religious tree which spread its branches to other parts of Enugu Diocese was planted, watered and nurtured". Eke Parish was the cradle of the faith that has today become Diocese of NSuka, Abakaliki, Makurdi, Oturkpo, Ogoja, and Enugu. It was in 1921 that the Roman Catholic Mission Set up a School/Church at Oke-Oil Ali-Awgu (St. Michael's Awgu) which attracted over 100 converts in less than one year. They were received and harboured by Late Chief Chukwunta Nwachumolie. The first teacher to St. Michael's School/Church, Awgu, one Mr. Ofodiamah from Ogwashi-Ukwu of the Present Delta State of Nigeria. And the first Holy Mass at St. Michael's Awgu was at Oke-Ali-Ohaja Awgu by Rev. Fr. Grandin.
                On other hand, the missionary movement into Awgu from Uturu, Okigwe was orchestered by the existence/construction of railway from Enugu to Port-Harcourt in 1915. This made that Ndeabor Railway stations a whirlpool of so many itineraries, mercantile and even evangelical interactions. This created and provided a pastoral relationship between St. Michael's Awgu and the Roman Catholic Mission at Uturu, Okigwe (which was nearer to Awgu than Eke) which was already established in 1912. In 1926, Rev. Fr. Treich, the first priest to minister to the faithful at St. Michael's Awgu from Uturu prepared Catechumen who received their First Holy Communion on 21st October, 1926. However, given the foundation of another Church in Awgu region at Mmaku, which was raised to a parish status in 1922, St. Michael's Awgu was under Mnaku Parish until 1948 when she was made a parish too. Out of these two sources (Eke and Uturu), the church continued to spread in Awgu areas with joyful yet uneasy circumstances, on both side of the missionaries and mission converts. There were days of thus-of-war between native ancestral religion and Christianity and of oscillation of people from old traditional civilization and the emerging one that is Christian and exotic. Given limited pastors and prevalent pressures from conflicting old and new faiths, it was really martyrdom like and heroic to be Christian then. But it was out if these rocky roots that today we rejoice to the harvest of a young, buoyant and vibrant Awgu ecclesiastical circumscription.
                Awgu was created a diocese by His Holiness, Pope Benedict XVI on the 8th July, 2005. On the 29th of September, it was canonically erected and Most Rev. John Ifeanyichukwu Okoye ordained and enthroned as its first bishop.</dd>
            </dl>
            </div>
          </div>
        </div>
      </section>